name: Tests
on: [ push, pull_request ]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Intall dependencies
        run:  npm install
      - name: Run tests
        run:  npm run tests